KrekelSchool/Models/Domain1/Gebruiker.cs
using System;
using System.Collections;

namespace KrekelSchool.Models.Domain1
{
    public class Gebruiker
    {


        public Gebruiker(string uname, string pswd, string naam)
        {
            Uname = uname;
            Pswd = pswd;
            Naam = naam;
            
        }



        public virtual Mediatheek Mediatheek { get; set; }
        public Gebruiker()
        {
          
        }
        
       
        public string Uname { get; set; }
        public string Pswd { get; set; }
        public string Naam { get; set; }
        public int Id { get; set; }


    }
}

KrekelSchool/Models/ViewModels/GebruikerViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using KrekelSchool.Models.Domain1;

namespace KrekelSchool.Models.ViewModels
{
    public class GebruikerViewModel
    {
        [Display(Name = "Gebruikersnaam")]
        public string Uname { get; set; }
        [Display(Name = "Wachtwoord")]
        public string Pswd { get; set; }
        [Display(Name = "Naam")]
        [Required(ErrorMessage = "{0} is verplicht!!")]
        public string Naam { get; set; }
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public int Id { get; set; }

        public GebruikerViewModel()
        {
            
        }

        public GebruikerViewModel(Gebruiker gebruiker)
        {
            Uname = gebruiker.Uname;
            Pswd = gebruiker.Pswd;
            Naam = gebruiker.Naam;
            Id = gebruiker.Id;
        }
    }
}

KrekelSchool/Controllers/GebruikerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using KrekelSchool.Models.DAL;
using KrekelSchool.Models.Domain1;
using KrekelSchool.Models.ViewModels;

namespace KrekelSchool.Controllers
{
    public class GebruikerController : Controller
    {
        private MediatheekRepository MediatheekRepository;
        private Mediatheek Mediatheek;

       
            
            
        private GebruikerRepository Repository;
        
        public GebruikerController(GebruikerRepository repository,MediatheekRepository repos)
        {
            Repository = repository;
            MediatheekRepository = repos;
            Mediatheek = repos.GetMediatheek();
        }
        // GET: Gebruiker
        [HttpGet]
        public ActionResult LogIn(string zoek, User user)
        {
            ViewBag.Title = "Gebruiker-Lijst";
            ViewBag.Message = "Geef gebruikersnaam of naam in als zoekcriteria.";
            IEnumerable<Gebruiker> gebruikers = Mediatheek.Gebruikers.OrderBy(g => g.Naam);
            IEnumerable<GebruikerViewModel> gvm = gebruikers.Select(g => new GebruikerViewModel(g)).ToList();
            if (!String.IsNullOrEmpty(zoek))
            {
                gvm = gvm.Where(s => s.Naam.ToLower().Contains(zoek.ToLower()) ||
                    s.Uname.ToLower().Contains(zoek.ToLower()));
            }
            return View(new GebruikerViewModel());
        }
        [HttpPost]
        public ActionResult LogIn(GebruikerViewModel model,User user)
        {
            
            
            //if (ModelState.IsValid)
            //{
                var gebruiker = Mediatheek.Gebruikers.First(g => g.Uname == model.Uname && g.Pswd == model.Pswd);
               if (gebruiker != null) {
                   user.LogInUser(gebruiker);
                   ViewBag.gebruiker = gebruiker.Uname;
                   return RedirectToAction("Item","Item");
                //}
                
            }

            
            ModelState.AddModelError("", "Foutief paswoord of gebruikersnaam.");
            return RedirectToAction("LogIn"); 

        }
        [HttpGet]
        public ActionResult Edit(int id,User user)
        {
            Gebruiker gebruiker = Mediatheek.Gebruikers.First(b => b.Id == id);
            if (gebruiker == null)
                return HttpNotFound();
            ViewBag.Title = "Gebruiker: " + gebruiker.Naam + " aanpassen";
            return PartialView("Add", new GebruikerViewModel(gebruiker));
        }

        [HttpPost]
        public ActionResult Edit(int id, GebruikerViewModel gvm,User user)
        {
            
            try
            {
                if (ModelState.IsValid)
                {
                    Gebruiker gebruiker = Mediatheek.Gebruikers.First(b => b.Id == id);
                    MapToGebruiker(gvm, gebruiker);
                    MediatheekRepository.SaveChanges();
                    TempData["Message"] = String.Format("{0} werd aangepast.", gebruiker.Naam);
                    return RedirectToAction("Gebruikers");
                }
            }
            catch (System.Data.Entity.Validation.DbEntityValidationException dbEx)
            {

                Exception raise = dbEx;
                foreach (var validationErrors in dbEx.EntityValidationErrors)
                {
                    foreach (var validationError in validationErrors.ValidationErrors)
                    {
                        string message = string.Format("{0}: {1}", validationErrors.Entry.Entity.ToString(), validationError.ErrorMessage);

                        raise = new InvalidOperationException(message, raise);
                    }
                }
                throw raise;
            }
            return PartialView("Add",gvm);
        }

        private void MapToGebruiker(GebruikerViewModel gvm, Gebruiker gebruiker)
        {
            gebruiker.Id = gvm.Id;
            gebruiker.Naam = gvm.Naam;
            gebruiker.Uname = gvm.Uname;
            gebruiker.Pswd = gvm.Pswd;
        }
        
        [HttpGet]
        public ActionResult AddVrijwilliger()
        {
            Vrijwilliger gebruiker = new Vrijwilliger();
            ViewBag.Title = "Boek toevoegen";
            return PartialView(new GebruikerViewModel(gebruiker));
        }

        [HttpPost]
        public ActionResult AddVrijwilliger(GebruikerViewModel gvm , User user)
        {
            
            try
            {
                if (ModelState.IsValid)
                {
                    Vrijwilliger gebruiker = new Vrijwilliger();
                    MapToGebruiker(gvm, gebruiker);
                    Mediatheek.VoegGebruikerToe(gebruiker);
                    MediatheekRepository.SaveChanges();
                   
                    TempData["Message"] = String.Format("{0} werd gecreëerd.", gebruiker.Naam);
                    return RedirectToAction("Gebruikers");
                }
            }
            catch (System.Data.Entity.Validation.DbEntityValidationException dbEx)
            {

                Exception raise = dbEx;
                foreach (var validationErrors in dbEx.EntityValidationErrors)
                {
                    foreach (var validationError in validationErrors.ValidationErrors)
                    {
                        string message = string.Format("{0}: {1}", validationErrors.Entry.Entity.ToString(), validationError.ErrorMessage);

                        raise = new InvalidOperationException(message, raise);
                    }
                }
                throw raise;
            }
            return PartialView(gvm);
        }
        [HttpGet]
        public ActionResult AddMedewerker()
        {
            Medewerker gebruiker = new Medewerker();
            ViewBag.Title = "Boek toevoegen";
            return PartialView(new GebruikerViewModel(gebruiker));
        }

        [HttpPost]
        public ActionResult AddMedewerker(GebruikerViewModel gvm, User user)
        {
            
            try
            {
                if (ModelState.IsValid)
                {
                    Medewerker gebruiker = new Medewerker();
                    MapToGebruiker(gvm, gebruiker);
                    Mediatheek.VoegGebruikerToe(gebruiker);

                    MediatheekRepository.SaveChanges();
                    
                    TempData["Message"] = String.Format("{0} werd gecreëerd.", gebruiker.Naam);
                    return RedirectToAction("Gebruikers");
                }
            }
            catch (System.Data.Entity.Validation.DbEntityValidationException dbEx)
            {

                Exception raise = dbEx;
                foreach (var validationErrors in dbEx.EntityValidationErrors)
                {
                    foreach (var validationError in validationErrors.ValidationErrors)
                    {
                        string message = string.Format("{0}: {1}", validationErrors.Entry.Entity.ToString(), validationError.ErrorMessage);

                        raise = new InvalidOperationException(message, raise);
                    }
                }
                throw raise;
            }
            return PartialView(gvm);
        }
        [HttpGet]
        public ActionResult Remove(int id)
        {
            
            Gebruiker gebruiker = Mediatheek.Gebruikers.First(b => b.Id == id);
            if (gebruiker == null)
                return HttpNotFound();
            ViewBag.Title = "Gebruiker: " + gebruiker.Naam + " verwijderen";
            return PartialView(new GebruikerViewModel(gebruiker));
        }

        [HttpPost, ActionName("Remove")]
        public ActionResult RemoveConfirm(int id)
        {
           
            try
            {
                Gebruiker gebruiker = Mediatheek.Gebruikers.First(b => b.Id == id);
                if (gebruiker == null)
                    return HttpNotFound();
                Mediatheek.VerwijderGebruiker(gebruiker);
                MediatheekRepository.SaveChanges();
                TempData["Message"] = String.Format("{0} werd verwijderd!", gebruiker.Naam);
            }
            catch (Exception ex)
            {
                TempData["error"] = ViewBag.ErrorMessage = "Verwijderen van boek mislukt. Probeer opnieuw. " +
                           "Als de problemen zich blijven voordoen, contacteer de  administrator.";
            }
            return RedirectToAction("LogIn");
        }

        public ActionResult Gebruikers(User user)
        {
            
            IEnumerable<Gebruiker> gebruikers= Mediatheek.Gebruikers.AsEnumerable();
            
            IEnumerable<GebruikerViewModel> gvm =gebruikers.Select(g => new GebruikerViewModel(g)).ToList();
            return View(gvm);
        }
    }
}

KrekelSchool/Views/Gebruiker/Add.cshtml
@model KrekelSchool.Models.ViewModels.GebruikerViewModel
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/jqueryval")
@{
    ViewBag.Title = "Add";
}
@{
    ViewBag.Title = Model.Id == 0 ? "Gebruiker Toevoegen" : "Gebruiker Wijzigen";
}
<h2 class="modalFormTitle">@ViewBag.Title</h2>
<h4>@ViewBag.Message</h4>
<hr />
@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal modalForm">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Uname, htmlAttributes: new { @class = "control-label col-md-2 label" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Uname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Uname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Pswd, htmlAttributes: new { @class = "control-label col-md-2 label" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Pswd, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Pswd, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Naam, htmlAttributes: new { @class = "control-label col-md-2 label" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Naam, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Naam, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value=" " class="btn btn-default addOk" style="margin: 0" />
                <button type="button" class="btn btn-default btnClose" data-dismiss="modal"></button>
            </div>
        </div>
    </div>
}

<script type="text/javascript">
    $(function () {
        $('addOk').click(function () {
            $(this).removeData('bs.modal');
            //location.reload();
        });
        $('.btnClose').click(function () {
            location.reload();
        });
    });
</script>

KrekelSchool/Views/Gebruiker/AddMedewerker.cshtml
@model KrekelSchool.Models.ViewModels.GebruikerViewModel
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/jqueryval")
@{
    ViewBag.Title = Model.Id == 0 ? "Medewerker Toevoegen" : "Medewerker Wijzigen";
}

<h2 class="modalFormTitle">@ViewBag.Title</h2>
<h4>@ViewBag.Message</h4>
<hr />
@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal modalForm">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Uname, htmlAttributes: new { @class = "control-label col-md-2 label" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Uname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Uname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Pswd, htmlAttributes: new { @class = "control-label col-md-2 label" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Pswd, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Pswd, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Naam, htmlAttributes: new { @class = "control-label col-md-2 label" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Naam, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Naam, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value=" " class="btn btn-default addOk" style="margin: 0" />
                <button type="button" class="btn btn-default btnClose" data-dismiss="modal"></button>
            </div>
        </div>
    </div>
}

<script type="text/javascript">
    $(function () {
        $('addOk').click(function () {
            $(this).removeData('bs.modal');
            //location.reload();
        });
        $('.btnClose').click(function () {
            location.reload();
        });
    });
</script>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

KrekelSchool/Views/Gebruiker/AddVrijwilliger.cshtml
@model KrekelSchool.Models.ViewModels.GebruikerViewModel
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/jqueryval")
@{
    ViewBag.Title = Model.Id == 0 ? "Vrijwilliger Toevoegen" : "Vrijwilliger Wijzigen";
}


<h2 class="modalFormTitle">@ViewBag.Title</h2>
<h4>@ViewBag.Message</h4>
<hr />
@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal modalForm">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Uname, htmlAttributes: new { @class = "control-label col-md-2 label" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Uname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Uname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Pswd, htmlAttributes: new { @class = "control-label col-md-2 label" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Pswd, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Pswd, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Naam, htmlAttributes: new { @class = "control-label col-md-2 label" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Naam, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Naam, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value=" " class="btn btn-default addOk" style="margin: 0" />
                <button type="button" class="btn btn-default btnClose" data-dismiss="modal"></button>
            </div>
        </div>
    </div>
}

<script type="text/javascript">
    $(function () {
        $('addOk').click(function () {
            $(this).removeData('bs.modal');
            //location.reload();
        });
        $('.btnClose').click(function () {
            location.reload();
        });
    });
</script>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

KrekelSchool/Views/Gebruiker/Gebruikers.cshtml
@model IEnumerable<KrekelSchool.Models.ViewModels.GebruikerViewModel>

@{
    ViewBag.Title = "Gebruikers";
}

<h2>Gebruikers</h2>
<div class="row">
    @using (Html.BeginForm("Gebruikers", "Gebruiker", FormMethod.Get))
    {
        <div class="col-md-8 ">
            @Html.TextBox("zoek", null, new { @class = "form-control formListSearch" })
            <br />
        </div>
    }
    <p>
        @Html.ActionLink(" ", "AddVrijwilliger", null, new { @class = "modal-link btn btn-success btnAddVolu" })
        @Html.ActionLink(" ", "AddMedewerker", null, new { @class = "modal-link btn btn-success btnAddEmpl" })
    </p>
    
<table class="table">
    <tr>
        <th></th>
        <th>
            @Html.DisplayNameFor(model => model.Uname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Pswd)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Naam)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.ActionLink(" ", "Edit", new { id = item.Id }, new { @class = "modal-link btn btn-success btnEdit " })

                @Html.ActionLink(" ", "Remove", new { id = item.Id }, new { @class = "modal-link btn btn-success btnRmv" })
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Uname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Pswd)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Naam)
            </td>

        </tr>
    }

</table>
</div>

KrekelSchool/Views/Gebruiker/LogIn.cshtml
@model KrekelSchool.Models.ViewModels.GebruikerViewModel

@{
    ViewBag.Title = "Log in";
}
<div class="banner">
    <img src="~/images/krekelBanner.png" alt="de krekel banner" />
</div>

<h2>@ViewBag.Title.</h2>
<div class="row">
    <div class="col-md-12">
        <section id="loginForm">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                <h4>Gebruik uw Gebruikersnaam en wachtwoord om in te loggen.</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">

                    @Html.LabelFor(m => m.Uname, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.Uname, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Uname, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Pswd, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.PasswordFor(m => m.Pswd, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Pswd, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Log in" class="btn btn-default" />
                    </div>
                </div>
            }
        </section>
    </div>
</div>

KrekelSchool/Views/Gebruiker/Remove.cshtml
@model KrekelSchool.Models.ViewModels.GebruikerViewModel


<div>
    <h2 class="modalFormTitle">@ViewBag.Title</h2>
    <h4>Bent u zeker dat u @Model.Uname, @Model.Naam wil verwijderen?</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Uname) :
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Uname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pswd) :
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pswd)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Naam) :
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Naam)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
    <div class="form-actions no-color">
        <input type="submit" value=" " class="btn btn-default addOk" />
        <button type="button" class="btn btn-default btnClose" data-dismiss="modal"></button>
    </div>
    }
</div>
<script type="text/javascript">
    $(function () {
        $('addOk').click(function () {
            $('#modal-container').modal('hide');
            location.reload();
        });
        $('.btnClose').click(function () {
            location.reload();
        });
    });
</script>