KrekelSchool/Models/Domain1/Verteltas.cs
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace KrekelSchool.Models.Domain1
{
    public class Verteltas : Item
    {
        //public ICollection<Item> Items { get; set; }
        //public virtual Categorie Categorie { get; set; }
        //public ICollection<Boek> Boeken { get; set; }
        //public ICollection<Cd> Cds { get; set; }
        //public ICollection<Dvd> Dvds { get; set; }
        //public ICollection<Spel> Spellen { get; set; }

        //public Verteltas(string naam, bool beschikbaar, string beschrijving, int leeftijd, string imgUrl, IEnumerable<Categorie> categories) : base(naam, beschikbaar, beschrijving, leeftijd, imgUrl, categories)
        //{
        //}

        public Verteltas(string naam, bool beschikbaar, string beschrijving, int leeftijd, string imgUrl, Categorie categorie)
            : base(naam, beschikbaar, beschrijving, leeftijd, imgUrl, categorie)
        {
        }

        public Verteltas(string naam, bool beschikbaar, string beschrijving, int leeftijd, string imgUrl)
            : base(naam, beschikbaar, beschrijving, leeftijd, imgUrl)
        {
        }

        public Verteltas() { }

        public ICollection<Item> Items { get; set;}

        public void ItemToevoegen(Item item)
        {
            Items.Add(item);
        }

        public void ItemsToevoegen(ICollection<Item> items)
        {
            foreach (Item item in items)
            {
                ItemToevoegen(item);
            }
        }

        public void ItemVerwijderen(Item item)
        {
            Items.Remove(item);
        }
       
    }
}

KrekelSchool/Models/ViewModels/VerteltasViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Dynamic;
using System.Linq;
using System.Web;
using KrekelSchool.Models.Domain1;

namespace KrekelSchool.Models.ViewModels
{
    public class VerteltasViewModel
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public int Id { get; set; }

        [Display(Name = "Naam")]
        [Required(ErrorMessage = "{0} is verplicht!!")]
        public string Naam { get; set; }

        [Display(Name = "Beschrijving")]
        public string Beschrijving { get; set; }

        [Display(Name = "Beschikbaar")]
        public bool Beschikbaar { get; set; }
        public int Leeftijd { get; set; }

        public ICollection<Categorie> Categories { get; set; }
        public IEnumerable<Item> Items { get; set; } 

        public VerteltasViewModel(Verteltas item)
        {
            Id = item.Id;
            Naam = item.Naam;
            Beschrijving = item.Beschrijving;
            Beschikbaar = item.Beschikbaar;
            Leeftijd = item.Leeftijd;
            Items = item.Items;

        }

        public VerteltasViewModel()
        {
            
        }
    }
}

KrekelSchool/Controllers/VerteltasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using KrekelSchool.Models.DAL;
using KrekelSchool.Models.Domain1;
using KrekelSchool.Models.ViewModels;
using WebGrease.Css.Extensions;

namespace KrekelSchool.Controllers
{
    public class VerteltasController : Controller
    {
        private MediatheekRepository MediatheekRepository;
        private Mediatheek Mediatheek;

        public VerteltasController(MediatheekRepository repository)
        {
            MediatheekRepository = repository;
            Mediatheek = repository.GetMediatheek();
        }
        [HttpGet]
        public ActionResult Index(VoorlopigeUitlening voorlopige , User user,string zoek)
        {
            ViewBag.Title = "Verteltassen-Lijst";
            ViewBag.Message = "Geef ID, naam,... in als zoekcriteria.";
            IEnumerable<Verteltas> Items = Mediatheek.Verteltass.AsEnumerable();
            //BoekRepository.FindAll().OrderBy(b => b.Naam);
            IEnumerable<VerteltasViewModel> vvm = Items.Select(b => new VerteltasViewModel(b)).ToList();
            if (!String.IsNullOrEmpty(zoek))
            {
                vvm = vvm.Where(b => b.Naam.ToLower().Contains(zoek.ToLower()) ||
                    b.Leeftijd.ToString().Contains(zoek.ToLower()));
            }
            return View(new ItemScreenViewModel(voorlopige, vvm, user));
        }
        public ActionResult VerteltasDetail(int id)
        {
            Verteltas verteltas = Mediatheek.Verteltass.First(b => b.Id == id);
            if (verteltas == null)
                return HttpNotFound();
            ViewBag.Title = "Details van: ";
            ViewBag.Message = verteltas.Naam;
            return PartialView(new VerteltasViewModel(verteltas));
        }
        [HttpGet]
        public ActionResult VerteltasToevoegen()
        {
            Verteltas verteltas = new Verteltas();
            ViewBag.Title = "Verteltas toevoegen";
            return PartialView(new VerteltasViewModel(verteltas));
        }

        [HttpPost]
        public ActionResult VerteltasToevoegen(VerteltasViewModel vvm)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Verteltas verteltas = new Verteltas();
                    MapToVerteltas(vvm, verteltas);
                    Mediatheek.VoegVerteltasToe(verteltas);
                    MediatheekRepository.SaveChanges();
                    //  BoekRepository.SaveChanges();
                    TempData["Message"] = String.Format("{0} werd gecreëerd.", verteltas.Naam);
                    return RedirectToAction("Index");
                }
            }
            catch (System.Data.Entity.Validation.DbEntityValidationException dbEx)
            {

                Exception raise = dbEx;
                foreach (var validationErrors in dbEx.EntityValidationErrors)
                {
                    foreach (var validationError in validationErrors.ValidationErrors)
                    {
                        string message = string.Format("{0}: {1}", validationErrors.Entry.Entity.ToString(), validationError.ErrorMessage);

                        raise = new InvalidOperationException(message, raise);
                    }
                }
                throw raise;
            }
            return PartialView(vvm);
        }
        [HttpGet]
        public ActionResult VerteltasAanpassen(int id)
        {
            Verteltas verteltas = Mediatheek.Verteltass.First(b => b.Id == id);
            if (verteltas == null)
                return HttpNotFound();
            ViewBag.Title = "Boek: " + verteltas.Naam + " aanpassen";
            return PartialView("VerteltasToevoegen", new VerteltasViewModel(verteltas));
        }

        [HttpPost]
        public ActionResult VerteltasAanpassen(int id, VerteltasViewModel bvm)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Verteltas verteltas = Mediatheek.Verteltass.First(b => b.Id == id);
                    MapToVerteltas(bvm, verteltas);
                    MediatheekRepository.SaveChanges();
                    TempData["Message"] = String.Format("{0} werd aangepast.", verteltas.Naam);
                    return RedirectToAction("Index");
                }
            }
            catch (System.Data.Entity.Validation.DbEntityValidationException dbEx)
            {

                Exception raise = dbEx;
                foreach (var validationErrors in dbEx.EntityValidationErrors)
                {
                    foreach (var validationError in validationErrors.ValidationErrors)
                    {
                        string message = string.Format("{0}: {1}", validationErrors.Entry.Entity.ToString(), validationError.ErrorMessage);

                        raise = new InvalidOperationException(message, raise);
                    }
                }
                throw raise;
            }
            return PartialView("VerteltasToevoegen", bvm);
        }
        [HttpGet]
        public ActionResult VerteltasVerwijderen(int id)
        {
            Verteltas verteltas = Mediatheek.Verteltass.First(b => b.Id == id);
            if (verteltas == null)
                return HttpNotFound();
            ViewBag.Title = "Boek: " + verteltas.Naam + " verwijderen";
            return PartialView(new VerteltasViewModel(verteltas));
        }

        [HttpPost, ActionName("VerteltasVerwijderen")]
        public ActionResult BoekVerwijderenBevestig(int id)
        {
            try
            {
                Verteltas verteltas = Mediatheek.Verteltass.First(b => b.Id == id);
                if (verteltas == null)
                    return HttpNotFound();
                Mediatheek.VerwijderVerteltas(verteltas);
                MediatheekRepository.SaveChanges();
                TempData["Message"] = String.Format("{0} werd verwijderd!", verteltas.Naam);
            }
            catch (Exception ex)
            {
                TempData["error"] = ViewBag.ErrorMessage = "Verwijderen van boek mislukt. Probeer opnieuw. " +
                           "Als de problemen zich blijven voordoen, contacteer de  administrator.";
            }
            return RedirectToAction("Index");
        }
        
        private void MapToVerteltas(VerteltasViewModel vvm, Verteltas verteltas)
        {
            verteltas.Beschikbaar = vvm.Beschikbaar;
            verteltas.Beschrijving = vvm.Beschrijving;
            verteltas.Categories = vvm.Categories;
            verteltas.Leeftijd = vvm.Leeftijd;
            foreach (Item item in vvm.Items)
            {
                verteltas.Items.Add(item);
            }
        }
    }
}

KrekelSchool/Views/Verteltas/Index.cshtml
@using KrekelSchool.Models
@using Microsoft.Ajax.Utilities
@model  KrekelSchool.Models.ViewModels.ItemScreenViewModel

<h2>@(ViewBag.Title)</h2>
<h4>@ViewBag.Message</h4>
<hr />
@if (TempData["Succes"] != null)
{
    <h1>@TempData["Succes"]</h1>

}
<div class="row">

    @using (Html.BeginForm("Index", "Verteltas", FormMethod.Get))
    {
        <div class="col-md-8 ">
            <span>
                @Html.TextBox("zoek", null, new { @class = "form-control formListSearch" })
            </span>
        </div>
    }
    <div class="excelAdd">
        @using (Html.BeginForm("Index", "Verteltas", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <input type="file" name="file" />
            <input type="submit" value="" class="btn btn-default addOk" />
        }
    </div>


    @Html.ActionLink(" ", "VerteltasToevoegen", "Verteltas", null, new { @class = "modal-link btn btn-success btnAdd" })


    @*@if (Model.Voorlopige.Item != null || Model.Voorlopige.Lener != null)
    {
        <div class="col-md-4 gewenstItem">
            <h2>Gewenst boek</h2>
            <table>

                @if (Model.Voorlopige.Item != null)
                {
                    if (Model.Voorlopige.Item.ImgUrl == " " || Model.Voorlopige.Item.ImgUrl == null || Model.Voorlopige.Item.ImgUrl == "")
                    {
                        <tr>
                            <p>@Model.Voorlopige.Item.Naam</p>
                            <img src=" " alt=" " class="gewenstItemImg itemImgEmpty" />
                            <br />

                            @Html.ActionLink(" ", "VerwijderVoorlopigItem", new { id = @Model.Voorlopige.Item.Id }, new { @class = "btn btn-success btnRmv" })
                        </tr>
                    }
                    else
                    {
                        <tr>
                            <p>@Model.Voorlopige.Item.Naam</p>
                            <img src="@Model.Voorlopige.Item.ImgUrl" alt="@Model.Voorlopige.Item.Naam" class="gewenstItemImg" />
                            <br />
                            @Html.ActionLink(" ", "VerwijderVoorlopigItem", new { id = @Model.Voorlopige.Item.Id }, new { @class = "btn btn-success btnRmv" })
                        </tr>
                    }
                }
            </table>

            <h2>Aan</h2>
            <table>
                @if (Model.Voorlopige.Lener != null)
                {
                    <p>@(Model.Voorlopige.Lener.Naam + " " + Model.Voorlopige.Lener.Voornaam)</p>
                    <br />
                    @Html.ActionLink(" ", "VerwijderVoorlopigeLener", new { id = @Model.Voorlopige.Lener.Id }, new { @class = "btn btn-success btnRmv" })

                }

            </table>
            @if (Model.Voorlopige.Lener != null && Model.Voorlopige.Item != null)
            {
                @Html.ActionLink(" ", "AanvaardUitlening", null, new { @class = "btn btn-success addOk" })
            }
        </div>
    }*@





    @foreach (var p in Model.Boeken)
    {
        <div class="col-md-8 itemObj">
            <h2>@p.Naam</h2>
            @if (p.ImgUrl == " " || p.ImgUrl == null || p.ImgUrl == "")
            {
                <img src="" alt=" " class="itemImgEmpty" />
            }
            else
            {
                <img src="@p.ImgUrl" alt="@p.Naam" class="itemImg" />
            }
            <table>
                <tr>
                    <td class="pName">@Html.DisplayNameFor(model => p.Leeftijd) :</td>
                    <td class="pNameValue">+ @Html.DisplayFor(model => p.Leeftijd)</td>
                </tr>
                <tr>
                    <td class="pName">@Html.DisplayNameFor(model => p.Auteur) :</td>
                    <td class="pNameValue">@Html.DisplayFor(model => p.Auteur)</td>
                </tr>
                <tr>
                    <td class="pName">@Html.DisplayNameFor(model => p.Uitgever) :</td>
                    <td class="pNameValue">@Html.DisplayFor(model => p.Uitgever)</td>
                </tr>
                <tr>
                    <td class="pName">@Html.DisplayNameFor(model => p.Categorie.Beschrijving) :</td>
                    <td class="pNameValue">@Html.DisplayFor(model => p.Categorie.Beschrijving)</td>
                </tr>
                <tr>
                    <td class="pName">@Html.DisplayNameFor(model => p.Beschikbaar) :</td>
                    @if (p.Beschikbaar.Equals(true))
                    {
                        <td class="pNameValue"> Ja</td>;
                    }
                    else
                    {
                        <td class="pNameValue"> Geen Meer</td>;
                    }

                </tr>
                @*@foreach (var prop in p.GetType().GetProperties())
                    {
                        <tr>
                            <td class="pName">@prop.Name : </td>
                            <td>@p.GetType().GetProperty(prop.Name).GetValue(p)</td>
                        </tr>
                    }*@
                @Html.ActionLink(" ", "VerteltasAanpassen", new { id = p.Id }, new { @class = "modal-link btn btn-success btnEdit" })
                @Html.ActionLink(" ", "VerteltasDetail", new { id = p.Id }, new { @class = "modal-link btn btn-success btnDet" })
                @Html.ActionLink(" ", "VerteltasVerwijderen", new { id = p.Id }, new { @class = "modal-link btn btn-success btnRmv" })
                @Html.ActionLink(" ", "", new { id = p.Id }, new { @class = "btn btn-success btnLeen" })

            </table>
        </div>
    }

</div>

KrekelSchool/Views/Verteltas/VerteltasDetail.cshtml
@model KrekelSchool.Models.ViewModels.VerteltasViewModel

<div>
    <h2 class="modalFormTitle">@ViewBag.Title</h2>
    <h4>@ViewBag.Message</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Naam) :
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Naam)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Beschrijving) :
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Beschrijving)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Beschikbaar) :
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Beschikbaar)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Leeftijd) :
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Leeftijd)
        </dd>

    </dl>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <button type="button" class="btn btn-default btnClose" data-dismiss="modal"></button>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(function () {
        $('.btnClose').click(function () {
            $('#modal-container').modal('hide');
            location.reload();
        });
    });
</script>

KrekelSchool/Views/Verteltas/VerteltasToevoegen.cshtml
@model KrekelSchool.Models.ViewModels.VerteltasViewModel

@Scripts.Render("~/bundles/jqueryval")
@{
    ViewBag.Title = Model.Id == 0 ? "Boek Toevoegen" : "Boek Wijzigen";
    ViewBag.http = "HTTP://";
}

<h2 class="modalFormTitle">@ViewBag.Title</h2>
<h4>@ViewBag.Message</h4>
<hr />
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal modalForm">
        <h4>VerteltasViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Naam, htmlAttributes: new { @class = "control-label col-md-2 label" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Naam, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Naam, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Beschrijving, htmlAttributes: new { @class = "control-label col-md-2 label" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Beschrijving, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Beschrijving, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Beschikbaar, htmlAttributes: new { @class = "control-label col-md-2 label" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Beschikbaar)
                    @Html.ValidationMessageFor(model => model.Beschikbaar, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Leeftijd, htmlAttributes: new { @class = "control-label col-md-2 label" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Leeftijd, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Leeftijd, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<script type="text/javascript">
    $(function () {
        $('.addOk').click(function () {
            $(this).removeData('bs.modal');
            //location.reload();
        });
        $('.btnClose').click(function () {
            location.reload();
        });
    });
</script>

KrekelSchool/Views/Verteltas/VerteltasVerwijderen.cshtml
@model KrekelSchool.Models.ViewModels.VerteltasViewModel


<div>
    <h2>@ViewBag.Title</h2>
    <h4>Bent u zeker dat u @Model.Naam wil verwijderen?</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Naam) :
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Naam)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Beschrijving) :
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Beschrijving)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Beschikbaar) :
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Beschikbaar)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Leeftijd) :
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Leeftijd)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value=" " class="btn btn-default addOk" />
        <button type="button" class="btn btn-default btnClose" data-dismiss="modal"></button>
    </div>
    }
</div>
<script type="text/javascript">
    $(function () {
        $('addOk').click(function () {
            $('#modal-container').modal('hide');
            location.reload();
        });
        $('.btnClose').click(function () {
            location.reload();
        });
    });
</script>